logger:
  level: info

database:
  # Postgres DSN for Nakama. Disable SSL for local dev only.
  address: "postgresql://nakama:localdev@db:5432/nakama?sslmode=disable"

runtime:
  path: "/nakama/data/modules"

console:
  port: 7351
