logger:
  level: info

database:
  # Postgres DSNs for Nakama. Disable SSL for local dev only.
  address:
    - "postgresql://nakama:localdev@db:5432/nakama?sslmode=disable"

runtime:
  path: "/nakama/data/modules"
  env:
    - "tienlen_bots_enabled=true"
    - "tienlen_bot_min_delay_sec=1"
    - "tienlen_bot_max_delay_sec=3"

console:
  port: 7351
