// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: tienlen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card_Suit int32

const (
	Card_SUIT_SPADES   Card_Suit = 0
	Card_SUIT_CLUBS    Card_Suit = 1
	Card_SUIT_DIAMONDS Card_Suit = 2
	Card_SUIT_HEARTS   Card_Suit = 3
)

// Enum value maps for Card_Suit.
var (
	Card_Suit_name = map[int32]string{
		0: "SUIT_SPADES",
		1: "SUIT_CLUBS",
		2: "SUIT_DIAMONDS",
		3: "SUIT_HEARTS",
	}
	Card_Suit_value = map[string]int32{
		"SUIT_SPADES":   0,
		"SUIT_CLUBS":    1,
		"SUIT_DIAMONDS": 2,
		"SUIT_HEARTS":   3,
	}
)

func (x Card_Suit) Enum() *Card_Suit {
	p := new(Card_Suit)
	*p = x
	return p
}

func (x Card_Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Card_Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_tienlen_proto_enumTypes[0].Descriptor()
}

func (Card_Suit) Type() protoreflect.EnumType {
	return &file_tienlen_proto_enumTypes[0]
}

func (x Card_Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Card_Suit.Descriptor instead.
func (Card_Suit) EnumDescriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{0, 0}
}

// Card represents a single Tien Len card.
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          Card_Suit              `protobuf:"varint,1,opt,name=suit,proto3,enum=tienlen.v1.Card_Suit" json:"suit,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"` // 0..12 where 3=0, A=11, 2=12
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_tienlen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetSuit() Card_Suit {
	if x != nil {
		return x.Suit
	}
	return Card_SUIT_SPADES
}

func (x *Card) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// Client -> Server requests
type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_tienlen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{1}
}

type PlayCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayCardsRequest) Reset() {
	*x = PlayCardsRequest{}
	mi := &file_tienlen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCardsRequest) ProtoMessage() {}

func (x *PlayCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCardsRequest.ProtoReflect.Descriptor instead.
func (*PlayCardsRequest) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{2}
}

func (x *PlayCardsRequest) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type PassTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassTurnRequest) Reset() {
	*x = PassTurnRequest{}
	mi := &file_tienlen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassTurnRequest) ProtoMessage() {}

func (x *PassTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassTurnRequest.ProtoReflect.Descriptor instead.
func (*PassTurnRequest) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{3}
}

type RequestNewGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestNewGameRequest) Reset() {
	*x = RequestNewGameRequest{}
	mi := &file_tienlen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestNewGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNewGameRequest) ProtoMessage() {}

func (x *RequestNewGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNewGameRequest.ProtoReflect.Descriptor instead.
func (*RequestNewGameRequest) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{4}
}

// Server -> Client events
type PlayerJoinedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Seat          int32                  `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"` // 1-based seat number
	Owner         bool                   `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoinedEvent) Reset() {
	*x = PlayerJoinedEvent{}
	mi := &file_tienlen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinedEvent) ProtoMessage() {}

func (x *PlayerJoinedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinedEvent.ProtoReflect.Descriptor instead.
func (*PlayerJoinedEvent) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerJoinedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerJoinedEvent) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerJoinedEvent) GetOwner() bool {
	if x != nil {
		return x.Owner
	}
	return false
}

type PlayerLeftEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeftEvent) Reset() {
	*x = PlayerLeftEvent{}
	mi := &file_tienlen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeftEvent) ProtoMessage() {}

func (x *PlayerLeftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeftEvent.ProtoReflect.Descriptor instead.
func (*PlayerLeftEvent) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerLeftEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GameStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStartedEvent) Reset() {
	*x = GameStartedEvent{}
	mi := &file_tienlen_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartedEvent) ProtoMessage() {}

func (x *GameStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartedEvent.ProtoReflect.Descriptor instead.
func (*GameStartedEvent) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{7}
}

func (x *GameStartedEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type HandDealtEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hand          []*Card                `protobuf:"bytes,1,rep,name=hand,proto3" json:"hand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandDealtEvent) Reset() {
	*x = HandDealtEvent{}
	mi := &file_tienlen_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandDealtEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandDealtEvent) ProtoMessage() {}

func (x *HandDealtEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandDealtEvent.ProtoReflect.Descriptor instead.
func (*HandDealtEvent) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{8}
}

func (x *HandDealtEvent) GetHand() []*Card {
	if x != nil {
		return x.Hand
	}
	return nil
}

type CardPlayedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cards         []*Card                `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardPlayedEvent) Reset() {
	*x = CardPlayedEvent{}
	mi := &file_tienlen_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardPlayedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardPlayedEvent) ProtoMessage() {}

func (x *CardPlayedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardPlayedEvent.ProtoReflect.Descriptor instead.
func (*CardPlayedEvent) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{9}
}

func (x *CardPlayedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CardPlayedEvent) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type TurnPassedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnPassedEvent) Reset() {
	*x = TurnPassedEvent{}
	mi := &file_tienlen_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnPassedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnPassedEvent) ProtoMessage() {}

func (x *TurnPassedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnPassedEvent.ProtoReflect.Descriptor instead.
func (*TurnPassedEvent) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{10}
}

func (x *TurnPassedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GameEndedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinishOrder   []string               `protobuf:"bytes,1,rep,name=finish_order,json=finishOrder,proto3" json:"finish_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEndedEvent) Reset() {
	*x = GameEndedEvent{}
	mi := &file_tienlen_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEndedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEndedEvent) ProtoMessage() {}

func (x *GameEndedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tienlen_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEndedEvent.ProtoReflect.Descriptor instead.
func (*GameEndedEvent) Descriptor() ([]byte, []int) {
	return file_tienlen_proto_rawDescGZIP(), []int{11}
}

func (x *GameEndedEvent) GetFinishOrder() []string {
	if x != nil {
		return x.FinishOrder
	}
	return nil
}

var File_tienlen_proto protoreflect.FileDescriptor

const file_tienlen_proto_rawDesc = "" +
	"\n" +
	"\rtienlen.proto\x12\n" +
	"tienlen.v1\"\x92\x01\n" +
	"\x04Card\x12)\n" +
	"\x04suit\x18\x01 \x01(\x0e2\x15.tienlen.v1.Card.SuitR\x04suit\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\"K\n" +
	"\x04Suit\x12\x0f\n" +
	"\vSUIT_SPADES\x10\x00\x12\x0e\n" +
	"\n" +
	"SUIT_CLUBS\x10\x01\x12\x11\n" +
	"\rSUIT_DIAMONDS\x10\x02\x12\x0f\n" +
	"\vSUIT_HEARTS\x10\x03\"\x12\n" +
	"\x10StartGameRequest\":\n" +
	"\x10PlayCardsRequest\x12&\n" +
	"\x05cards\x18\x01 \x03(\v2\x10.tienlen.v1.CardR\x05cards\"\x11\n" +
	"\x0fPassTurnRequest\"\x17\n" +
	"\x15RequestNewGameRequest\"V\n" +
	"\x11PlayerJoinedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\x05R\x04seat\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\bR\x05owner\"*\n" +
	"\x0fPlayerLeftEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"(\n" +
	"\x10GameStartedEvent\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\"6\n" +
	"\x0eHandDealtEvent\x12$\n" +
	"\x04hand\x18\x01 \x03(\v2\x10.tienlen.v1.CardR\x04hand\"R\n" +
	"\x0fCardPlayedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x05cards\x18\x02 \x03(\v2\x10.tienlen.v1.CardR\x05cards\"*\n" +
	"\x0fTurnPassedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x0eGameEndedEvent\x12!\n" +
	"\ffinish_order\x18\x01 \x03(\tR\vfinishOrderB\x12Z\x10tienlen/proto;pbb\x06proto3"

var (
	file_tienlen_proto_rawDescOnce sync.Once
	file_tienlen_proto_rawDescData []byte
)

func file_tienlen_proto_rawDescGZIP() []byte {
	file_tienlen_proto_rawDescOnce.Do(func() {
		file_tienlen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tienlen_proto_rawDesc), len(file_tienlen_proto_rawDesc)))
	})
	return file_tienlen_proto_rawDescData
}

var file_tienlen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tienlen_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tienlen_proto_goTypes = []any{
	(Card_Suit)(0),                // 0: tienlen.v1.Card.Suit
	(*Card)(nil),                  // 1: tienlen.v1.Card
	(*StartGameRequest)(nil),      // 2: tienlen.v1.StartGameRequest
	(*PlayCardsRequest)(nil),      // 3: tienlen.v1.PlayCardsRequest
	(*PassTurnRequest)(nil),       // 4: tienlen.v1.PassTurnRequest
	(*RequestNewGameRequest)(nil), // 5: tienlen.v1.RequestNewGameRequest
	(*PlayerJoinedEvent)(nil),     // 6: tienlen.v1.PlayerJoinedEvent
	(*PlayerLeftEvent)(nil),       // 7: tienlen.v1.PlayerLeftEvent
	(*GameStartedEvent)(nil),      // 8: tienlen.v1.GameStartedEvent
	(*HandDealtEvent)(nil),        // 9: tienlen.v1.HandDealtEvent
	(*CardPlayedEvent)(nil),       // 10: tienlen.v1.CardPlayedEvent
	(*TurnPassedEvent)(nil),       // 11: tienlen.v1.TurnPassedEvent
	(*GameEndedEvent)(nil),        // 12: tienlen.v1.GameEndedEvent
}
var file_tienlen_proto_depIdxs = []int32{
	0, // 0: tienlen.v1.Card.suit:type_name -> tienlen.v1.Card.Suit
	1, // 1: tienlen.v1.PlayCardsRequest.cards:type_name -> tienlen.v1.Card
	1, // 2: tienlen.v1.HandDealtEvent.hand:type_name -> tienlen.v1.Card
	1, // 3: tienlen.v1.CardPlayedEvent.cards:type_name -> tienlen.v1.Card
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tienlen_proto_init() }
func file_tienlen_proto_init() {
	if File_tienlen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tienlen_proto_rawDesc), len(file_tienlen_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tienlen_proto_goTypes,
		DependencyIndexes: file_tienlen_proto_depIdxs,
		EnumInfos:         file_tienlen_proto_enumTypes,
		MessageInfos:      file_tienlen_proto_msgTypes,
	}.Build()
	File_tienlen_proto = out.File
	file_tienlen_proto_goTypes = nil
	file_tienlen_proto_depIdxs = nil
}
